### ISSUE TITLE
Figure out how to encompass the programatic parts of the specifications into the scim-spec-protocol and scim-spec-schema modules

### ISSUE THREAD

**Issue by smoyer64** [PennState/SCIMple-Identity#1]
There are parts of the specifications, such as which error codes should be returned in which instances that are relatively easy to code in the implementation.  Is there a way to put them into the specification modules instead?

**Comment by ussmith** [comment]
I think we can say that this is done

**Comment by ussmith** [comment]
Closing based on 20 April 16 comment
