### ISSUE TITLE
Pick a name for the PSU SCIM project

### ISSUE THREAD

**Issue by smoyer64** [PennState/SCIMple-Identity#10]
Candidates:
-   [ ] sCimpy
-   [x] SCIMple Identify

**Comment by shawnmckinney** [comment]
SCIMle?

**Comment by ussmith** [comment]
This has been decided and accepted by Apache Directory

**Comment by smoyer64** [comment]
I had forgotten this was even an issue ... and thinking about SCIMpy, doesn't that look like the name of a Python library?
