### ISSUE TITLE
Work to get ready for the SCIM interop

### ISSUE THREAD

**Issue by smoyer64** [PennState/SCIMple-Identity#12]
Tasks are (grouped):

**Operational**
-   [ ] Push updated scim-server-common (and dependencies) to GitHub
-   [ ] Build updated scim-server-common on Jenkins (before building TIER)

**ServiceProviderConfig**
-   [x] 1.1 Retrieve service provider config w/out authz
-   [ ] ~~1.2 Retrieve service provider config w/ authz~~

**ResourceTypes**
-   [x] 2.1 List resource types
-   [x] 2.2 Retrieve a single resource type

**Schemas**
-   [x] 3.1 List schemas
-   [x] 3.2 Retrieve a single schema

**User Creation (POST)**
-   [x] 4.1 Create a user - verify attributes are saved and 201 response with a full user is returned
-   [x] 4.2 Create a user with a multi-valued complex attribute
-   [x] 4.3 Create a user with a $ref attribute
-   [ ] 4.4 Create a user with an immutable attribute
-   [ ] 4.5 Create a user with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 4.6 Create a user with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 4.7 Create a user with attributes not supported by server (extension and core) - should be ignored See issue 14
-   [ ] 4.8 Create a user with missing required attributes - should fail - See issue 13
-   [x] 4.9 Create a user with a non-unique value for a unique attribute - should fail

**User update (PUT)**
-   [x] 5.1 Update user - verify attributes are saved and 200 response with a full user is returned
-   [x] 5.2 Update a user with a multi-valued complex attribute
-   [x] 5.3 Update a user with a $ref attribute
-   [ ] 5.4 Update an immutable attribute that was previously null - value should be set
-   [ ] 5.5 Update an immutable attribute that has a value, setting it to the same value - should succeed
-   [ ] 5.6 Update an immutable attribute that has a value, setting it to a different value - should fail
-   [ ] 5.7 Update a readOnly attribute - should be ignored
-   [ ] 5.8 Update a user with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 5.9 Update a user with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [x] 5.10 Update a user with attributes not supported by server (extension and core) - should be ignored
-   [ ] 5.11 Update a user with missing required attributes - should fail
-   [ ] 5.12 Update a user with a non-unique value for a unique attribute - should fail
-   [x] 5.13 Update a user with non-matching If-Match etag header - should return a 412 status code and not update the user
-   [x] 5.14 Update a user with matching If-Match etag header - should update

**User update (PATCH)**
-   [ ] 6.1 ~~Update a simple attribute with PATCH (replace)~~
-   [ ] 6.2 ~~Update a multi-valued attribute with PATCH (replace)~~
-   [ ] 6.3 ~~Add a value to a multi-valued attribute with PATCH (add)~~
-   [ ] 6.4 ~~Remove a value from a multi-valued attribute with PATCH (remove)~~
-   [ ] 6.5 ~~Update a complex multi-valued address with a non-ambiguous filter - addresses[type eq “home” and locality eq “Redwood Shores”]~~
-   [ ] 6.6 ~~Update a complex multi-valued address with an ambiguous filter - addresses.type eq “home” and addresses.locality eq “Redwood Shores”~~
-   [ ] 6.7 ~~Update a user with non-matching If-Match etag header using PATCH - should return a 412 status code and not update the user~~

*\* User retrieval (GET)**
-   [x] 7.1 Retrieve a user - full user should be returned.  Verify no writeOnly attributes (eg - password) are returned
-   [x] 7.2 Retrieve a user with If-None-Match etag that matches - should return 304
-   [x] 7.3 Retrieve a user with If-None-Match etag that does not match - should return user
-   [ ] 7.4 Retrieve a user with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 7.5 Retrieve a user with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [x] 7.6 Retrieve a user that does not exist - should return a 404
-   [ ] 7.7 Retrieve a user with a filter query param that matches the user
-   [ ] 7.8 Retrieve a user with a filter query param that does not match the user

**User listing/search (GET)**
-   [x] 8.1 Retrieve full list of users (no filters or count) - results should be capped by maxResults
-   [ ] 8.2 Retrieve a list of users with count and startIndex - should return paged result with correct total
-   [ ] 8.3 Retrieve a list of users with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 8.4 Retrieve a list of users with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 8.5 Retrieve a list of users filtered with a simple attribute
-   [ ] 8.6 Retrieve a list of users filtered with a complex attribute value (name.familyName)
-   [ ] 8.7 Retrieve a list of users filtered with a multi-valued attribute value (emails.value)
-   [ ] 8.8 Retrieve a list of users filtered with a complex multi-valued grouping operator - addresses[type eq “home” and locality eq “Redwood Shores”]
-   [ ] 8.9 Retrieve full list of users with POST to /Users/.search (no filters or count) - results should be capped by maxResults
-   [ ] 8.10 Retrieve a list of users with POST to /Users/.search with count and startIndex - should return paged result with correct total
-   [ ] 8.11 Retrieve a list of users with POST to /Users/.search with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 8.12 Retrieve a list of users with POST to /Users/.search with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 8.13 Retrieve a list of users with POST to /Users/.search filtered with a simple attribute
-   [ ] 8.14 Retrieve a list of users with POST to /Users/.search filtered with a complex attribute value (name.familyName)
-   [ ] 8.15 Retrieve a list of users with POST to /Users/.search filtered with a multi-valued attribute value (emails.value)
-   [ ] 8.16 Retrieve a list of users with POST to /Users/.search filtered with a complex multi-valued grouping operator - addresses[type eq “home” and locality eq “Redwood Shores”]

**User /me (GET)**
-   [ ] 9.1 Retrieve /me with a credential that maps to a user

**User delete (DELETE)**
-   [ ] 10.1 Delete a user - verify that 204 is returned
-   [ ] 10.2 Delete a user with If-Match etag that matches - should delete user
-   [ ] 10.3 Delete a user with If-Match etag that does not match - should return a 412 status code and not delete the user
-   [ ] 10.4 Delete a user that has already been deleted - should return a 404
-   [ ] 10.5 Create a user with the same username as a previously deleted user - should succeed

*\* Multi-ResourceType search**
-   [ ] 11.1 Searching with POST /.search returns multiple resource types
-   [ ] 11.1 Searching with POST /.search with a filter that contains an attribute only defined on users excludes groups from the results

**Use Case Scenarious**
-   [ ] 12.1 POST to create a new user.  GET created user and PUT it with no changes.  GET user again and ensure it is unchanged
-   [ ] 12.2 POST to create a new user.  Attempt to login as user.
-   [ ] 12.3 Use PUT or PATCH to set active to false and attempt to login as user - should fail
-   [ ] 12.4 Delete user and attempt to login as user - should fail
-   [ ] 12.5 Add a user to a group
-   [ ] 12.6 Remove a user from a group

**Group Creation (POST)**
-   [ ] 13.1 Create a group - verify attributes are saved and 201 response with a full group is returned
-   [ ] 13.2 Create a group with a multi-valued complex attribute
-   [ ] 13.3 Create a group with a $ref attribute
-   [ ] 13.4 Create a group with an immutable attribute
-   [ ] 13.5 Create a group with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 13.6 Create a group with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 13.7 Create a group with attributes not supported by server (extension and core) - should be ignored
-   [ ] 13.8 Create a group with missing required attributes - should fail
-   [ ] 13.9 Create a group with a non-unique value for a unique attribute - should fail

**Group update (PUT)**
-   [ ] 14.1 Update group - verify attributes are saved and 200 response with a full group is returned
-   [ ] 14.2 Update a group with a multi-valued complex attribute
-   [ ] 14.3 Update a group with a $ref attribute
-   [ ] 14.4 Update an immutable attribute that was previously null - value should be set
-   [ ] 14.5 Update an immutable attribute that has a value, setting it to the same value - should succeed
-   [ ] 14.6 Update an immutable attribute that has a value, setting it to a different value - should fail
-   [ ] 14.7 Update a readOnly attribute - should be ignored
-   [ ] 14.8 Update a group with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 14.9 Update a group with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 14.10 Update a group with attributes not supported by server (extension and core) - should be ignored
-   [ ] 14.11 Update a group with missing required attributes - should fail
-   [ ] 14.12 Update a group with a non-unique value for a unique attribute - should fail
-   [ ] 14.13 Update a group with non-matching If-Match etag header - should return a 412 status code and not update the group
-   [ ] 14.14 Update a group with matching If-Match etag header - should update

**Group update (PATCH)**
-   [ ] 15.1 ~~Update a simple attribute with PATCH (replace)~~
-   [ ] 15.2 ~~Update a multi-valued attribute with PATCH (replace)~~
-   [ ] 15.3 ~~Add a value to a multi-valued attribute with PATCH (add)~~
-   [ ] 15.4 ~~Remove a value from a multi-valued attribute with PATCH (remove)~~
-   [ ] 15.5 ~~Update a complex multi-valued address with a non-ambiguous filter - addresses[type eq “home” and locality eq “Redwood Shores”]~~
-   [ ] 15.6 ~~Update a complex multi-valued address with an ambiguous filter - addresses.type eq “home” and addresses.locality eq “Redwood Shores”~~
-   [ ] 15.7 ~~Update a group with non-matching If-Match etag header using PATCH - should return a 412 status code and not update the user~~

*\* Group retrieval (GET)**
-   [ ] 16.1 Retrieve a group - full user should be returned.  Verify no writeOnly attributes (eg - password) are returned
-   [ ] 16.2 Retrieve a group with If-None-Match etag that matches - should return 304
-   [ ] 16.3 Retrieve a group with If-None-Match etag that does not match - should return user
-   [ ] 16.4 Retrieve a group with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 16.5 Retrieve a group with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 16.6 Retrieve a group that does not exist - should return a 404
-   [ ] 16.7 Retrieve a group with a filter query param that matches the user
-   [ ] 16.8 Retrieve a group with a filter query param that does not match the user

**Group listing/search (GET)**
-   [ ] 17.1 Retrieve full list of groups (no filters or count) - results should be capped by maxResults
-   [ ] 17.2 Retrieve a list of groups with count and startIndex - should return paged result with correct total
-   [ ] 17.3 Retrieve a list of groups with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 17.4 Retrieve a list of groups with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 17.5 Retrieve a list of groups filtered with a simple attribute
-   [ ] 17.6 Retrieve a list of groups filtered with a complex attribute value (name.familyName)
-   [ ] 17.7 Retrieve a list of groups filtered with a multi-valued attribute value (emails.value)
-   [ ] 17.8 Retrieve a list of groups filtered with a complex multi-valued grouping operator - addresses[type eq “home” and locality eq “Redwood Shores”]
-   [ ] 17.9 Retrieve full list of groups with POST to /Groups/.search (no filters or count) - results should be capped by maxResults
-   [ ] 17.10 Retrieve a list of groups with POST to /Groups/.search with count and startIndex - should return paged result with correct total
-   [ ] 17.11 Retrieve a list of groups with POST to /Groups/.search with attributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 17.12 Retrieve a list of groups with POST to /Groups/.search with excludedAttributes query param (both core and extended attributes) - verify only requested attributes are returned
-   [ ] 17.13 Retrieve a list of groups with POST to /Groups/.search filtered with a simple attribute
-   [ ] 17.14 Retrieve a list of groups with POST to /Groups/.search filtered with a complex attribute value (name.familyName)
-   [ ] 17.15 Retrieve a list of groups with POST to /Groups/.search filtered with a multi-valued attribute value (emails.value)
-   [ ] 17.16 Retrieve a list of groups with POST to /Groups/.search filtered with a complex multi-valued grouping operator - addresses[type eq “home” and locality eq “Redwood Shores”]

**Group delete (DELETE)**
-   [ ] 18.1 Delete a group - verify that 204 is returned
-   [ ] 18.2 Delete a group with If-Match etag that matches - should delete user
-   [ ] 18.3 Delete a group with If-Match etag that does not match - should return a 412 status code and not delete the group
-   [ ] 18.4 Delete a group that has already been deleted - should return a 404
-   [ ] 18.5 Create a group with the same username as a previously deleted user - should succeed

**Comment by ussmith** [comment]
this is OBE
