### ISSUE TITLE
Lombok is not consistently in the correct scope

### ISSUE THREAD

**Issue by ccrvincent** [PennState/SCIMple-Identity#47]
Lombok should be in scope `provided`, but it is in the `compile` scope in several modules.

This resulted in an issue in my project where H2 stored procedures are now trying to use Lombok to compile on a JRE (instead of a JDK) due to the transitive dependency, and failing because Lombok expects a JDK.

Changing the scope to `provided` breaks the Maven build for other modules due to expected inheritance, so it needs to be explicitly added to those modules.

I have a working change locally, will try to get a PR up once I've successfully tested.

**Comment by smoyer64** [comment]
Sorry about that ... we'll definitely apply that PR immediately since it's only supposed to be affecting the .class file generation.

**Comment by ccrvincent** [comment]
PR open.  Sorry about the inconsistent author information.

**Comment by smoyer64** [comment]
Thanks for submitting this PR - I've taken a brief look at it and will comment on several parts tomorrow.  Those of you with commit privilege please don't merge this just yet.

**Comment by paul-tinius** [comment]
Any update on this?
