### ISSUE TITLE
Throw UnableToUpdateResourceException for UpdateRequest.getResource() until applyPatchOperations() is fully implemented

### ISSUE THREAD

**Issue by heidielliott72** [PennState/SCIMple-Identity#49]
When calling the PATCH operation, the UpdateRequest.getResource() defaults to a method that applies all the patch operations to the original ScimResource whenever UpdateRequest.resource is null. Until this feature is fully implemented for the PATCH operation, throw an UnableToUpdateResourceException with the status of NOT_IMPLEMENTED whenever resource is null from the UpdateRequest.getResource() method.

**Comment by smoyer64** [comment]
Closed by commit https://github.com/PennState/SCIMple-Identity/commit/d0f03e78be9b9a8f928a5059879145def0b07708 in PR #50 with an additional specification compliance issue opened in #51.
