### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by paul-tinius** [PennState/SCIMple-Identity#52]
Wondering when 2.22 will be officially release?

@smoyer64

**Comment by smoyer64** [comment]
I would love to release this project more often but right now there aren't enough automated tests - we're working on tests for the partially implemented patch functionality and I'll talk to the others in the office about releasing when those are in place (soon).  We have quite a few projects that are using this library and much of our comfort with SCIMple being specification compliant comes from testing with these implementations.  Let's tentatively say within the next couple weeks.

**Comment by smoyer64** [comment]
@paul-tinius - 2.22 was released last evening.  Sorry for the delay - Github deprecated various weak ciphers which caused the JGitflow plugin to fail when writing back to Github.  @chrisharm found a fork of that project and there shouldn't be delays related to tooling anymore.

Out of curiosity, what are you using SCIMple-Identify for?  We'd love to know how to make the library more compliant, easier to use and as always we welcome pull requests to add features and fix bugs!.

**Comment by paul-tinius** [comment]
Great thank you for the update.

--
Paul Tinius
paul.tinius@gmail.com
